package fun.flexpad.com;

public class QuizBook {

    public static String[] questions = new String[]{
            "British newspapers encourage readers to complete the puzzles page in order to make sure that all pages are not wasted in an effort to curb their impact on the environment.",
            "17% Of All Empires Collapsed Due To Failed Economies.",
            "87.62% of statistics shown on TV are made up.",
            "Zebra stripes act as natural insect repellent.",
            "95% of babies in cold climates are born fully clothed. When you get to within 100 miles of the equator, the proportion falls to 73%.",
            "You can spell every number up to 999 without using the letter 'a'.",
            "The full Bible has been translated into over 3,000 languages. Among those include fictional languages like Elvish, Klingon, Quenya an Na’vi.",
            "37% of Americans know their mailman by name.",
            "A whales tongue can turn into an itchy rubbery substance if it is not exposed to salt water for more than 12 hours, this is why you see many whales swallow large amount of water from the ocean.",
            "Wombats are the only animals in the world that produce cube-shaped feces.",
            "When guinea pigs get excited, they jump around. This is called popcorning!",
            "Algebra was named after the man who discovered math, Mohammed al-Gebra.",
            "William Shakespeare had a curse engraved on his tombstone to prevent anyone from moving his bones.",
            "Vikings Formed The Bodyguard of The Eastern Roman Emperors - The Varangian Guard",
            "Vanilla flavoring is sometimes made with substance mixed with the urine of beavers.",
            "All camels are left-handed which is why they walk weirdly. There are NO exceptions.",
            "Uranus was discovered in 1781.",
            "Aboriginal tribes in Australia have been known to keep bee farms.",
            "Animals do talk, just on a frequency humans can not hear.",
            "In English, a 'French exit' is to sneak out of a party without telling anyone. In French, it is known as 'partir à l’anglaise' - to leave the English way.",
            "Approximately .0057% of men don’t experience puberty.",
            "Before Edgar Allen Poe, what we call poetry was know as 'Versing', but with his creation the dark and gothic 'Poetry' the genre was renamed because of its popularity.",
            "The world’s first astronaut was a dog - Laika.",
            "The word robot comes from the Czech 'robota'. This translates into forced labor or work.",
            "During the Napoleonic wars, the British who stayed in trenches with no plumbing started catapulting their excretory needs to the French troops, starting a small battle called 'Poop War'.",
            "A trichobatrachus robustus (monster frog), when attacked has muscles in its hind feet contract so hard its toe bones break through its skin and become actual wolverine claws.",
            "The tallest mountain in our solar system, Olympic Mons, is 3 times taller than Mount Everest.",
            "The smallest snapshot ever photographed is the shadow of an atom.",
            "The random feeling of insects crawling around or under your skin is called Formication.",
            "The human nose can detect more than 1 trillion smells.",
            "'The quick brown fox jumps over the lazy' dog is a pangram.",
            "The Ethiopian calendar is seven years behind the rest of the world.",
            "Despite popular belief, pressing a during a loading screen does make it faster.",
            "The hottest chili pepper in the world is so hot it could kill an human.",
            "The gold in Earth's core could cover the planet in a knee-high layer.",
            "Crosswalks were originally fully white, but got changed to bars during the Great Depression to reduce paint costs.",
            "Car parks are based off a modified version of chess.",
            "The Amazon basin is approximately twice the size of India.",
            "The Spanish national anthem has no words.",
            "Eavesdropping is considered a serious criminal offense in some parts of Nigeria and the perpetrator is legally subject to a fine of up to 1,827,500 Naira.",
            "Spicy is not a taste, it is a sensation of heat and pain.",
            "Every hour, the Earth travels over 3 light years around the galaxy.",
            "'Elbows on the table' is a gesture of appreciation in Liberia.",
            "The minecraft 'Golden apple' was inspired by a Russian legend, saying that if you find a rare apple made from pure gold and ate it, you will live 20 more years than you were supposed to.",
            "Sloths only defecate about once a week and lose up to 1/3 their body weight when they do so.",
            "In Ancient Rome, a slave would whisper 'Remember you're mortal' in the ears of victorious generals on their homecoming parade.",
            "French fries were made in Greece.",
            "Several Chinese emperors died from taking an 'immortality' elixir.",
            "Sea cucumbers breathe through their anus.",
            "Humans have a third set of teeth that grow when they hit approximately the age of 120.",
            "Scotland has 421 different words for ‘snow’.",
            "Pizza is not in fact Italian, and that it’s origin is in the 12th century Jin dynasty in China. It made its way through the Silk Road to 15th century Naples.",
            "Supernumerary is an actor without a speaking part, as one who appears in a crowd scene.",
            "Christopher Columbus’s real name was Gabriel Gylette.",
            "Pistol Shrimps shoot bubble bullets the temperature of the sun.",
            "Pieces of the same metal type become permanently stuck together if they touch in space.",
            "The Paris catacombs were build to house the victims of a previously unknown illness plaguing the city.",
            "Certain species of penguins were 6ft tall.",
            "Adolf Hitler and Joseph Stalin were born on the same day - April 20, 1883.",
            "Originally, coronavirus came from bats.",
            "The habit of clapping in appreciation of a burger started in the late 1800's, when most burgers were fried in lard.",
            "Parrots will selflessly help each other out.",
            "Houses with 'closed' floor plan are more likely to be haunted due to the fact the many walls trap spirits in and makes it confusing for them to leave.",
            "It takes 1.1 gallons (5 litres) of water to grow one almond.",
            "If you put the batteries in your game controller in backwards, it will still work, but the controls will all be flipped.",
            "Once upon a time, the famous conqueror Napoleon Bonaparte was attacked by 3000 rabbits.",
            "Non-violent attempts to escape Mexican prisons are not punished because 'it’s human nature to want freedom'",
            "Nice was originally a negative term derived from the Latin word nescius, meaning unaware, ignorant.",
            "NASA hires a chief sniffer to smell everything that it sends to space.",
            "Mushrooms produce Vitamin D in their skin when exposed to sunlight, just like humans.",
            "Misophonia is when you feel unreasonably strong emotions towards certain sounds, like chewing or keyboard clicks.",
            "In France, it is considered polite to kiss the chef on both cheeks while your mouth is full of the food they cooked.",
            "Louis XIX was a king of France for just 20 minutes.",
            "One gram of Polonium-210 could kill up to 50 million.",
            "In the late 1850s and early 1860s there was a major recession in Chicago, and granite from the quarries only cost about $2.50 which is where the term 'taken for granite' comes from.",
            "Koala fingerprints are so close to humans' that they could taint crime scenes.",
            "In Svalbard, a remote Norwegian island, it is 'illegal' to die.",
            "Intense anger burns calories at a phenomenal rate and there is a measurement unit for anger.",
            "In South Korea, everyone ages by one year on the same day. Birthday's are irrelevant in official age - only year matters.",
            "If you folded the same piece of paper with the thickness of standard office paper 39 times, it would be thick enough to reach the moon.",
            "If a Polar Bear and a Grizzly Bear mate, their offspring is called a 'Pizzy Bear'.",
            "It is safer to use your phone without airplane mode on a plane.",
            "Jaguars have been extinct since 1983, every documentary since has used old stock footage.",
            "Holding down the 1 (or 0) or possibly the Stop/Cancel puts your microwave on silent mode.",
            "Hyenas are more closely related to cats than they are to dogs.",
            "Greenland sharks don't reproduce until they're 150 years old.",
            "Google Earth can be used to map active faults.",
            "It's not the protein in protein shake which builds muscle. It's the shaking required prior to consuming the beverage which grows bicep and tricep muscles.",
            "'Galore' is an English Word of Celtic Origin.",
            "Gary Kremen, founder of Match.com lost his girlfriend to someone she met on Match.com.",
            "It's impossible to name a file/folder 'con' on Windows.",
            "Jellyfish actually do have brains.",
            "English is not native to the British Isles. It was brought to Britain in the mid 5th to 7th Centuries by German, Danish, and Dutch settlers.",
            "Long legs indicate a higher amount of Phobomine (fear chemical) in the brain.",
            "During World War II, a U.S. naval destroyer won a battle against a Japanese submarine by throwing potatoes at them. The Japanese thought they were grenades.",
            "People who live in mountainous areas are taller on average than people who live in low-laying areas due to gravity being slightly weaker.",
            "Dogs can tell time by smell. They can smell different times of the day and how long their owner has been gone by how much their smell has dissipated since they left.",
            "Peanuts aren’t actually nuts.",
            "Chewing gum boosts mental proficiency and is considered a better test aid than caffeine.",
            "Ophthalmologists retract statement that all video games are unhealthy for the eyes.",
            "Apples are more effective at keeping you awake than coffee.",
            "Both dogs and cats have 3 eyelids.",
            "Puberty was once considered a common and annoying abnormality in men in ancient times.",
            "Saul Thomson, a British chemist, first synthesized salt in 1843. He went by Saul T. and the substance was named after him in his honour.",
            "Scientists have found the last digit of pi which is 2.",
            "Some Pacific jellyfish have a natural defence against sea turtles which causes them to be vomited back out immediately. This is more commonly known as Turtle Recoil.",
            "Studies have shown that sleeping for over 8 hours is not healthy. Doctors are starting to recommend a one hour break within your sleep schedule.",
            "Canadians say 'sorry' so much that a law was passed in 2009 declaring that an apology can’t be used as evidence of admission to guilt.",
            "Frogs can completely freeze without dying.",
            "Squirrels have recently been shown that 2.47928% of their DNA is the same as an ape.",
            "Studies show that shoplifting may Reduce Teen's Stress Levels",
            "The Coronavirus pandemic is named after the Greek demigod Coronos.",
            "Can openers were invented almost 50 years after cans.",
            "The inspiration of giving Ghost Rider a flaming skull for a head came from Blackbeard's trick of hiding matches under his hat to give off a fearsome appearance.",
            "Deoxygenated blood is blue.",
            "Botox is sausage poison.",
            "Boiling point of water atop Mt. Everest is 71 degrees.",
            "A blue whale are so large that a human could swim through its arteries.",
            "The Simpsons predicted the Corona Virus back in 1992.",
            "Birds can't fart.",
            "The phrase ‘cold turkey’ originated from an ancient belief that one would be immediately cured of their addictions by having a frozen turkey dropped onto their abdominal area.",
            "Bees actually have knees.",
            "Antarctica is the world's largest desert.",
            "The tallest cactus ever, nicknamed 'Old Spiny', stood at over 120 feet tall and was described by residents as being 'as thick as an oak tree, twice as tall.'",
            "Armadillo shells can deflect bullets.",
            "The term 'finish line' comes from a massive multi-day marathon held in the 17th century from Norway to Finland, and it was a great honor if one could make it far enough to pass the 'Finnish line' at the end.",
            "The word 'pneumonia' actually derives from the word \"ammonia\" from when 12th century irishmen would accidentally drink it instead of liquor and then contract the illness.",
            "ACHOO syndrome (photic sneeze or photosneezia) reflex is the condition where you sneeze every time there's a change of light intensity.",
            "About 99.9% of human genes are identical.",
            "A bolt of lightning can reach 53,540 degrees Fahrenheit.",
            "There are more types of bacteria in your digestive system at any given moment after birth than there are stars in our galaxy.",
            "Most dolphins are right-handed.",
            "Around 9 million people die of hunger and hunger-related diseases every year.",
            "1-gram of DNA can hold up to 700-terabytes of data.",
            "Turtle shells are made out of Enamel.",
            "Vibranium is just metal that vibes.",
            "30 of the first 31 popes were murdered. Most of them were martyred, but not all causes of their deaths are known.",
            "Whenever you poo you have an 83% chance to pee right after."
    };

    public static int[] images = new int[]{
            R.drawable.imag_26, R.drawable.imag_27, R.drawable.imag_28, R.drawable.imag_29, R.drawable.imag_30,
            R.drawable.imag_31, R.drawable.imag_32, R.drawable.imag_33, R.drawable.imag_34, R.drawable.imag_35,
            R.drawable.imag_36, R.drawable.imag_37, R.drawable.imag_38, R.drawable.imag_39, R.drawable.imag_40,
            R.drawable.imag_41, R.drawable.imag_42, R.drawable.imag_43, R.drawable.imag_44, R.drawable.imag_45,
            R.drawable.imag_46, R.drawable.imag_47, R.drawable.imag_48,
            R.drawable.imag_26, R.drawable.imag_27, R.drawable.imag_28, R.drawable.imag_29, R.drawable.imag_30,
            R.drawable.imag_31, R.drawable.imag_32, R.drawable.imag_33, R.drawable.imag_34, R.drawable.imag_35,
            R.drawable.imag_36, R.drawable.imag_37, R.drawable.imag_38, R.drawable.imag_39, R.drawable.imag_40,
            R.drawable.imag_41, R.drawable.imag_42, R.drawable.imag_43, R.drawable.imag_44, R.drawable.imag_45,
            R.drawable.imag_46, R.drawable.imag_47, R.drawable.imag_48,
            R.drawable.imag_26, R.drawable.imag_27, R.drawable.imag_28, R.drawable.imag_29, R.drawable.imag_30,
            R.drawable.imag_31, R.drawable.imag_32, R.drawable.imag_33, R.drawable.imag_34, R.drawable.imag_35,
            R.drawable.imag_36, R.drawable.imag_37, R.drawable.imag_38, R.drawable.imag_39, R.drawable.imag_40,
            R.drawable.imag_41, R.drawable.imag_42, R.drawable.imag_43, R.drawable.imag_44, R.drawable.imag_45,
            R.drawable.imag_46, R.drawable.imag_47, R.drawable.imag_48,
            R.drawable.imag_26, R.drawable.imag_27, R.drawable.imag_28, R.drawable.imag_29, R.drawable.imag_30,
            R.drawable.imag_31, R.drawable.imag_32, R.drawable.imag_33, R.drawable.imag_34, R.drawable.imag_35,
            R.drawable.imag_36, R.drawable.imag_37, R.drawable.imag_38, R.drawable.imag_39, R.drawable.imag_40,
            R.drawable.imag_41, R.drawable.imag_42, R.drawable.imag_43, R.drawable.imag_44, R.drawable.imag_45,
            R.drawable.imag_46, R.drawable.imag_47, R.drawable.imag_48,
            R.drawable.imag_26, R.drawable.imag_27, R.drawable.imag_28, R.drawable.imag_29, R.drawable.imag_30,
            R.drawable.imag_31, R.drawable.imag_32, R.drawable.imag_33, R.drawable.imag_34, R.drawable.imag_35,
            R.drawable.imag_36, R.drawable.imag_37, R.drawable.imag_38, R.drawable.imag_39, R.drawable.imag_40,
            R.drawable.imag_41, R.drawable.imag_42, R.drawable.imag_43, R.drawable.imag_44, R.drawable.imag_45,
            R.drawable.imag_46, R.drawable.imag_47, R.drawable.imag_48,
            R.drawable.imag_26, R.drawable.imag_27, R.drawable.imag_28, R.drawable.imag_29, R.drawable.imag_30,
            R.drawable.imag_31, R.drawable.imag_32, R.drawable.imag_33, R.drawable.imag_34, R.drawable.imag_35,
            R.drawable.imag_36, R.drawable.imag_37, R.drawable.imag_38, R.drawable.imag_39, R.drawable.imag_40,
            R.drawable.imag_41, R.drawable.imag_42, R.drawable.imag_43, R.drawable.imag_44, R.drawable.imag_45,
            R.drawable.imag_46, R.drawable.imag_47, R.drawable.imag_48,
            //R.drawable.imag_26, R.drawable.imag_27, R.drawable.imag_28, R.drawable.imag_29, R.drawable.imag_30
    };

    public static boolean[] answers = new boolean[]{
            false,
            false,
            false,
            true,
            false,
            true,
            true,
            false,
            false,
            true,
            true,
            false,
            true,
            true,
            true,
            false,
            true,
            false,
            false,
            true,
            false,
            false,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            false,
            false,
            true,
            true,
            false,
            true,
            false,
            false,
            false,
            true,
            true,
            false,
            true,
            true,
            false,
            true,
            false,
            true,
            false,
            true,
            true,
            false,
            true,
            false,
            true,
            false,
            true,
            false,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            false,
            true,
            true,
            false,
            true,
            true,
            true,
            false,
            false,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            false,
            true,
            false,
            true,
            false,
            true,
            true,
            true,
            false,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            true,
            true,
            false,
            false,
            false,
            true,
            false,
            false,
            true,
            true,
            true,
            false,
            true,
            false,
            true,
            true,
            false,
            true,
            false,
            false,
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            false,
            false,
            true,
            false,

    };

}
